config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "workouts#index"

  resources :workouts
  resources :lifts
  resources :workout_lifts, only: [:new]
  resources :dashboard, only: [:index] do
    collection do
      get :chest_stats, as: :chest_stats
    end
  end
end

app/models/workout.rb
# == Schema Information
#
# Table name: workouts
#
#  id           :bigint           not null, primary key
#  completed_at :datetime         not null
#  style        :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_workouts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Workout < ApplicationRecord

  validates_presence_of :completed_at, :style

  belongs_to :user

  has_many :workout_lifts, dependent: :destroy

  accepts_nested_attributes_for :workout_lifts, reject_if: :all_blank, allow_destroy: true

  default_scope -> { order(completed_at: :desc) }

  before_validation :set_completed_at

  class << self

    def last_7_days
      by_date(days: 7)
    end

    def last_30_days
      by_date(days: 30)
    end

    def by_date(days:)
      Workout.where("completed_at > ?", days.days.ago)
    end

    def next_workout
      last_workout = self.first
      return Workout.create(style: WORKOUT_DEFAULT_STYLES.first) if last_workout.nil?
      last_index = WORKOUT_DEFAULT_STYLES.find_index(last_workout.style)
      next_style = WORKOUT_DEFAULT_STYLES[last_index + 1] if last_index
      next_style = WORKOUT_DEFAULT_STYLES.first if next_style.nil?
      Workout.where(style: next_style).last.dup || Workout.new(style: next_style)
    end
  end

  def nice_completed_at
    completed_at.strftime("%m/%d/%Y")
  end

  private

  def set_completed_at
    if self.completed_at.nil?
      self.completed_at = Time.now.in_time_zone("Mountain Time (US & Canada)")
    else
      self.completed_at = self.completed_at.in_time_zone("Mountain Time (US & Canada)")
    end
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  before_action :build_workout, only: [:new]

  def index
    @next_workout = Workout.next_workout
    @workouts = Workout.all.first(30)
  end

  def show
    redirect_to edit_workout_path(id: params[:id])
  end

  def edit
    @workout = Workout.find(params[:id])
  end

  def update
    @workout = Workout.find(params[:id])
    if @workout.update(workout_params)
      flash[:success] = "Workout Updated"
      redirect_to workouts_path
    else
      flash[:error] = @workout.errors.full_messages.to_sentence
      render "edit"
    end
  end

  def new
  end

  def create
    @workout = current_user.workouts.new(workout_params)
    if @workout.save
      flash[:success] = "Workout Created"
      redirect_to workouts_path
    else
      flash[:error] = @workout.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    Workout.find(params[:id]).destroy
    flash[:success] = "Workout Deleted"
    redirect_to workouts_path
  end

  private

  def workout_params
    params.require(:workout).permit(
      :completed_at,
      :style,
      workout_lifts_attributes: [
        :id, :lift_id, :workout_id, :_destroy,
        lift_sets_attributes: [ :id, :weight, :reps, :workout_lift_id, :style, :_destroy ]
      ],
    )
  end

  def build_workout
    if params[:style]
      @workout = Workout.new(style: params[:style])
    else
      @workout = Workout.new
    end

    @last_workout = Workout.where(style: @workout.style).first
    if @last_workout
      @workout.workout_lifts = @last_workout.workout_lifts.map { |wl| wl.dup }
    end
  end
end

app/helpers/workout_helper.rb
module WorkoutHelper
end

app/views/workouts/_form.html.erb
<div>
  <h1 class="heading">Workout</h1>
  <%= form_for @workout, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } do |workout_form| %>
    <%= workout_form.hidden_field :id, value: workout_form.object.id %>

    <div class="flex flex-column border-bottom mb-16">
      <%= workout_form.text_field :style, value: workout_form.object.style, autofocus: true, placeholder: 'Chest' %>
      <%= workout_form.date_field :completed_at, value: (workout_form.object.completed_at|| DateTime.now) %>
    </div>

    <div class="mb-32">
      <h3>Lifts</h3>

      <template data-nested-form-target="liftTemplate">
        <%= workout_form.fields_for :workout_lifts, WorkoutLift.new, child_index: 'NEW_RECORD' do |workout_lift_form| %>
          <%= render "workout_lifts/form", form: workout_lift_form %>
        <% end %>
      </template>

      <div id='lifts'>
        <%= workout_form.fields_for :workout_lifts do |workout_lifts_form| %>
          <%= render partial: 'workout_lifts/form', locals: { form: workout_lifts_form } %>
        <% end %>
      </div>
      <div>
        <button class="button" type="button" data-action="nested-form#addLift">Add Lift</button>
      </div>
    </div>

    <div>
      <%= workout_form.submit 'Save', class: 'button', style: 'width:100%' %>
    </div>
  <% end %>
  <% if @workout.id %>
    <%= button_to 'Delete', workout_path(@workout), method: :delete, class: 'me-8 button button-danger float-right', data: { turbo_confirm: 'Are you sure?'} %>
  <% end %>
</div>

app/views/workouts/edit.html.erb
<%= render partial: 'form' %>

app/views/workouts/index.html.erb
<div class="container">
  <h1 class="heading">Workouts</h1>
  <div class="mb-16">
    <div class="mb-16">
      <div>
        Last 7 Days <%= Workout.last_7_days.size %>
      </div>
      <div>
        Last 30 Days <%= Workout.last_30_days.size %>
      </div>
    </div>
    <div class="mx-8">
      <% WORKOUT_DEFAULT_STYLES.each do |style| %>
        <%= link_to "#{style.titleize}", new_workout_path(style: style), class: 'button' %>
      <% end %>
      <%= link_to "Other", new_workout_path, class: 'button' %>
    </div>
  </div>
  <div>
    <% @workouts.each do |workout| %>
      <div class="card mb-16">
        <div class="card-header">
          <%= link_to workout.style.titleize, edit_workout_path(workout) %>
          <%= workout.nice_completed_at %>
        </div>
        <div class="card-body">
          <% workout.workout_lifts.each do |workout_lift| %>
            <div class="mb-4 flex space-between mb-8">
              <div class="flex">
                <div class="margin-auto-y"><%= workout_lift.lift.name.titleize %></div>
              </div>
              <div class="flex space-between">
                <% workout_lift.lift_sets.each do |lift_set| %>
                  <%= render partial: 'lift_sets/show', locals: { lift_set: lift_set } %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="card-footer">
          <%= link_to 'Edit', edit_workout_path(workout), class: 'button' %>
          <%= link_to "Start #{workout.style.titleize}", new_workout_path, class: 'button' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/workouts/new.html.erb
<%= render partial: 'form' %>