config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "workouts#index"

  resources :workouts
  resources :lifts
  resources :workout_lifts, only: [:new]
  resources :dashboard, only: [:index] do
    collection do
      get :chest_stats, as: :chest_stats
    end
  end
end

app/models/lift.rb
# == Schema Information
#
# Table name: lifts
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Lift < ApplicationRecord

  default_scope -> { order(name: :asc) }
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/lifts_controller.rb
class LiftsController < ApplicationController

  def index
    @lifts = Lift.all
    @lift = Lift.new
  end

  def show
  end

  def edit
    @lift = Lift.find(params[:id])
  end

  def update
    Lift.find(params[:id]).update(lift_params)
    redirect_to lifts_path
  end

  def create
    lift = Lift.new(lift_params)
    lift.save
    redirect_to lifts_path
  end

  def destroy
  end

  private

  def lift_params
    params.require(:lift).permit(
      :name,
    )
  end
end

app/helpers/lifts_helper.rb
module LiftsHelper
end

app/views/lifts/_form.html.erb
<div>
  <%= form_for @lift do |form|  %>
    <div class="flex">
      <%= form.text_field :name, required: true, class: 'me-4 flex-2' %>
      <%= form.submit @lift.id ? 'Save' : 'Add' %>
    </div>
  <% end %>
</div>

app/views/lifts/edit.html.erb
<div>
  <h1 class="heading">Lift</h1>
  <%= render partial: 'form', locals: { lift: @lift } %>
</div>

app/views/lifts/index.html.erb
<div class="container">
  <h1 class="heading">Lifts</h1>
  <%= render partial: 'form' %>
  <div>
    <% @lifts.each do |lift| %>
      <div class="mb-16">
        <%= link_to lift.name, edit_lift_path(lift) %>
      </div>
    <% end %>
  </div>
</div>