config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "workouts#index"

  resources :workouts
  resources :lifts
  resources :workout_lifts, only: [:new]
  resources :dashboard, only: [:index] do
    collection do
      get :chest_stats, as: :chest_stats
    end
  end
end

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, msg| %>
  <div id='flash-messages' class="flash <%= type %>">
    <%= msg %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div id='navbar'>

  <div id='nav-hamburger'>
    <div></div>
    <div></div>
    <div></div>
  </div>

  <div class="left">
    <% if user_signed_in? %>
      <div><%= link_to 'Workouts', workouts_path %></div>
      <div><%= link_to 'Lifts', lifts_path %></div>
      <div><%= link_to 'Dashboard', dashboard_index_path %></div>
    <% end %>
  </div>

  <div class="right">
    <% if user_signed_in? %>
      <div><%= current_user.email %></div>
      <div><%= link_to 'Log Out', destroy_user_session_path, data: { turbo_method: :delete } %></div>
    <% else %>
      <div><%= link_to 'Log In', new_user_session_path %></div>
    <% end %>
  </div>
</div>

<div id='nav-menu' class="hidden">
  <div class="header">
    <% if user_signed_in? %>
      <div><%= link_to 'Workouts', workouts_path %></div>
      <div><%= link_to 'Lifts', lifts_path %></div>
      <div><%= link_to 'Dashboard', dashboard_index_path %></div>
    <% end %>
  </div>
  <div class="body">
    <% if user_signed_in? %>
      <div><%= current_user.email %></div>
    <% else %>
      <div>WHODAT</div>
    <% end %>
  </div>
  <div class="footer">
    <% if user_signed_in? %>
      <div><%= link_to 'Log Out', destroy_user_session_path, data: { turbo_method: :delete } %></div>
    <% else %>
      <div><%= link_to 'Log In', new_user_session_path %></div>
    <% end %>

  </div>


</div>